/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary": "#6b38d4",
              "secondary-fixed-dim": "#ffb0cd",
              "on-primary-container": "#fffbff",
              "on-tertiary": "#ffffff",
              "surface-container-highest": "#e2e2e3",
              "on-tertiary-fixed-variant": "#004883",
              "on-tertiary-container": "#fdfcff",
              "surface-tint": "#6d3bd7",
              "on-surface-variant": "#494454",
              "secondary-fixed": "#ffd9e4",
              "tertiary-fixed": "#d4e3ff",
              "secondary": "#b4136d",
              "inverse-surface": "#2f3132",
              "on-primary": "#ffffff",
              "on-secondary": "#ffffff",
              "inverse-primary": "#d0bcff",
              "on-tertiary-fixed": "#001c39",
              "on-error": "#ffffff",
              "surface-variant": "#e2e2e3",
              "inverse-on-surface": "#f0f1f2",
              "primary-fixed": "#e9ddff",
              "on-secondary-fixed-variant": "#8c0053",
              "on-surface": "#1a1c1d",
              "on-background": "#1a1c1d",
              "error": "#ba1a1a",
              "surface-bright": "#f9f9fa",
              "primary-fixed-dim": "#d0bcff",
              "surface-container-high": "#e8e8e9",
              "surface": "#f9f9fa",
              "secondary-container": "#fd56a7",
              "error-container": "#ffdad6",
              "background": "#f9f9fa",
              "tertiary-container": "#2676c8",
              "on-error-container": "#93000a",
              "surface-container-lowest": "#ffffff",
              "on-primary-fixed": "#23005c",
              "on-primary-fixed-variant": "#5516be",
              "on-secondary-fixed": "#3e0022",
              "outline-variant": "#cbc3d7",
              "outline": "#7b7486",
              "primary-container": "#8455ef",
              "surface-container-low": "#f3f3f4",
              "tertiary-fixed-dim": "#a4c9ff",
              "on-secondary-container": "#600037",
              "surface-container": "#eeeeef",
              "surface-dim": "#d9dadb",
              "tertiary": "#005da8"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "2xl": "1.5rem",
              "full": "9999px"
      },
      "spacing": {
              "container-max": "1280px",
              "gutter": "24px",
              "margin-mobile": "16px",
              "margin-desktop": "40px",
              "unit": "8px"
      },
      "fontFamily": {
              "label-md": ["Inter"],
              "label-sm": ["Inter"],
              "display-lg-mobile": ["Manrope"],
              "headline-sm": ["Manrope"],
              "headline-md": ["Manrope"],
              "display-lg": ["Manrope"],
              "body-md": ["Inter"],
              "body-lg": ["Inter"]
      },
      "fontSize": {
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.03em", "fontWeight": "600"}],
              "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
