spring.config.import=optional:file:.env[.properties],optional:file:OVAHealthAI/.env[.properties],optional:file:backend/OVAHealthAI/.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5432/OVAHealth_AI
spring.datasource.username=postgres
spring.datasource.password=0000


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:dummy-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:dummy-secret}
app.oauth2.redirect-uri=${OAUTH2_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}

