version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: ova-postgres

    environment:
      POSTGRES_DB: OVAHealth_AI
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot:
    build: .
    container_name: ova-springboot

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/OVAHealth_AI
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000

volumes:
  postgres_data: